import { SidebarNavigation } from "@/components/Navigation";
import { SidebarInset } from "@/components/ui/sidebar";
import { currentUser } from "@clerk/nextjs/server";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();

  if(!user) {
    redirect('/sign-in');
  }

  return (
    <>
      <SidebarNavigation />

      <SidebarInset className="!ml-3 transition-all !duration-300 ease-in-out">
        <main className="flex-1 overflow-auto p-6">{children}</main>
      </SidebarInset>
    </>
  );
}
