import { SidebarNavigation } from "@/components/Navigation";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <SidebarNavigation />
    <main className="flex-1 overflow-auto p-6">
      {children}
    </main>
    </>
  );
}
