import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex-1 flex flex-col gap-6 h-screen overflow-auto p-6 items-center justify-center">
      <h1 className="text-3xl font-bold">Welcome to Dashboard Tasker!</h1>
      {children}
    </main>
  );
}
